server:
  port: 9600
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: chat-web-admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
seata:
  application-id: serverAddr
  enabled: true
  tx-service-group: friend-chat-tx-group
  registry:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.discovery.server-addr}

  service:
    disable-global-transaction: false
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000
    connection-timer-repeat: 10000

friend-chat:
  admin:
    token:
      header: Authorization
      prefix: Bearer
      expire-time: 30m