server:
  port: 8090
spring:
  application:
    name: chat-admin-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: chat-web-admin
          uri: lb://chat-web-admin
          predicates:
            - Path=/**
      x-forwarded:
        for-enabled: false

      # 全局跨域
      globalcors:
        # 跨域配置(可以在代码里面处理允许跨域，也可在这里全局处理)
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - DELETE
              - PUT
              - HEAD
              - PATCH