server:
  port: 8080
spring:
  application:
    name: chat-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: chat-web-user
          uri: lb://chat-web-user
          predicates:
            - Path=/**
      x-forwarded:
        for-enabled: false